name: Test only

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Python 3.8
      uses: actions/setup-python@v3
      with: 
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: | 
        conda env update --file environment_test.yml --name base
    - name: Run tests. 
      run: |
        unittest discover